server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    locations: classpath:db/migration

